sequenceDiagram
    participant FE as Backoffice
    participant GW as API Gestion
    participant AUTH as Auth Service
    participant GAL as Galeries Service

    FE->>GW: POST /galeries [JWT] {titre, type, mise_en_page, [client_email]}
    GW->>AUTH: Valider JWT
    AUTH-->>GW: 200 OK
    GW->>GAL: Créer galerie
    GAL-->>GW: 201 Created {galerie_id}
    GW-->>FE: 201 Created